title: Introduction to Physical Oceanography
author: Robert Stewart
logo: docs/logo2.png

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: force
  stderr_output: remove # suppress warnings 

parse:
    myst_enable_extensions:  # default extensions to enable in the myst parser. 
    - html_admonition
    - html_image
    - amsmath
    - dollarmath

html:
  static_paths: 
    - "docs/static"
  use_repository_button: true
  use_issues_button: true
  extra_css:
    - docs/static/custom.css # it can be useful for specific designs

# Exclude patterns
exclude_patterns: [
  "README.md",
  "README.html",
  "**/README.md",
  "**/README.html"
]

sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    suppress_warnings: ["*"]
    nb_execution_show_tb: False
    html_static_path: ["docs/static"]
    bibtex_reference_style: author_year
  html_context:
    default_mode: light
  extra_extensions:
    - myst_nb

bibtex_bibfiles:
    - docs/references.bib

repository:
  url: https://github.com/alioacar/intro_to_po
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)
