# Table of contents

format: jb-book
root: docs/intro
options:
  numbered: True
chapters:
- file: notebooks/chapter1
- file: notebooks/chapter2
- file: notebooks/chapter3
- file: notebooks/chapter4
- file: notebooks/chapter5
- file: notebooks/chapter6
- file: notebooks/chapter7
- file: notebooks/chapter8
- file: notebooks/chapter9
- file: notebooks/chapter10
- file: notebooks/chapter11
- file: notebooks/chapter12
- file: notebooks/chapter13
- file: notebooks/chapter14
- file: notebooks/chapter15
- file: notebooks/chapter16
- file: notebooks/chapter17
- file: notebooks/chapter18
