name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches:
      - master  # or 'main', the branch you use for development

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache : 'pip'

      # Cache Cartopy downloads
      - name: Cache Cartopy data
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/cartopy
            ~/.cache/cartopy
          key: ${{ runner.os }}-cartopy-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-cartopy-

      # Cache Jupyter Book build
      - name: Cache Jupyter Book build
        uses: actions/cache@v3
        with:
          path: _build
          key: ${{ runner.os }}-jupyter-book-${{ hashFiles('**/*.ipynb', 'config/*.yml') }}
          restore-keys: |
            ${{ runner.os }}-jupyter-book-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build Jupyter Book
        run: |
          jupyter-book build . --config config/config.yml --toc config/toc.yml
          cd _build/html
          cp -r ../../docs .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html  # Replace with the correct build output directory
          publish_branch: gh-pages  # Deploy to the 'gh-pages' branch
          force_orphan: true  # Optional: creates an orphan branch if needed
